export default [ { "name": "start",
"title": "Building a web app with ES6", 
"short": "Start",
} ,{ "name": "intro",
"title": "Introduction", 
"short": "Intro",
} ,{ "name": "node",
"title": "Setting up with Node.js and NPM", 
"short": "Setup - Node.js and NPM",
} ,{ "name": "jspm",
"title": "Setting up jspm", 
"short": "Setup - jspm",
} ,{ "name": "grunt",
"title": "Setting up Grunt", 
"short": "Setup - Grunt",
} ,{ "name": "git",
"title": "Setting up with Git", 
"short": "Setup - Git",
} ];