export default [ { "name": "start",
"title": "Building a web app with ES6", 
"short": "Start",
} ,{ "name": "intro",
"title": "Introduction", 
"short": "Intro",
} ,{ "name": "tips",
"title": "Some tips before we start", 
"short": "Tips",
} ,{ "name": "install-node",
"title": "Installing Node.js and NPM", 
"short": "Install (Node.js and NPM)",
} ,{ "name": "install-jspm",
"title": "Installing jspm", 
"short": "Install (jspm)",
} ,{ "name": "install-grunt",
"title": "Installing Grunt", 
"short": "Install (Grunt)",
} ,{ "name": "install-git",
"title": "Installing Git", 
"short": "Install (Git)",
} ,{ "name": "clone-repo",
"title": "Cloning the skeleton repository", 
"short": "Git clone",
} ,{ "name": "setup-index",
"title": "Setting up index.html", 
"short": "Setup (index.html)",
} ,{ "name": "setup-angular",
"title": "Setting up Angular", 
"short": "Setup (Angular)",
} ,{ "name": "setup-router",
"title": "Setting up the router", 
"short": "Setup (Router)",
} ,{ "name": "navigation-directive",
"title": "Creating the navigation directive", 
"short": "Navigation (directive)",
} ];